app:
  name: "AI MT5 Trading Bot"
  version: "2.0.0"
  environment: "production"

mt5:
  broker: "Weltrade"
  auto_trading_enabled: true
  risk_per_trade_percent: 1.0
  max_open_positions: 3
  magic_number: 234000

market:
  symbols:
    # Forex Major Pairs
    - "EURUSD"
    - "GBPUSD"
    - "USDJPY"
    - "USDCHF"
    - "AUDUSD"
    - "NZDUSD"
    - "USDCAD"

    # Forex Minor & Exotic Pairs
    - "EURJPY"
    - "GBPJPY"
    - "EURGBP"

    # Commodities
    - "XAUUSD"  # Gold
    - "XAGUSD"  # Silver
    - "USOIL"   # Crude Oil

    # Indices
    - "US30"    # Dow Jones
    - "NAS100"  # Nasdaq
    - "SPX500"  # S&P 500

    # Crypto (if available)
    - "BTCUSD"
    - "ETHUSD"

  timeframes:
    - "1m"
    - "5m"
    - "15m"
    - "1h"
    - "4h"
    - "1d"

ai_model:
  type: "ensemble"  # ensemble, xgboost, random_forest

  features:
    technical_indicators:
      - "RSI"
      - "MACD"
      - "Bollinger_Bands"
      - "EMA"
      - "SMA"
      - "ADX"
      - "Stochastic"
      - "ATR"
      - "Volume"
      - "OBV"

    price_action:
      - "candlestick_patterns"
      - "support_resistance"
      - "trend_lines"

  ensemble:
    models:
      - type: "random_forest"
        weight: 0.35
      - type: "xgboost"
        weight: 0.35
      - type: "pattern_based"
        weight: 0.30

  training:
    lookback_period: 100  # candles
    validation_split: 0.2
    epochs: 50
    batch_size: 32

signals:
  confidence_threshold: 0.75  # 75% minimum confidence
  min_score: 80  # out of 100

  filters:
    min_volume_24h: 1000000  # USD
    max_spread_percent: 0.5
    liquidity_check: true

  risk_management:
    max_signals_per_day: 10
    max_signals_per_pair: 3
    min_risk_reward: 2.0
    stop_loss_atr_multiplier: 1.5
    take_profit_levels: [1.5, 2.0, 3.0]

  types:
    - "BUY"
    - "SELL"

telegram:
  enabled: true
  message_format: "rich"  # simple, rich, chart
  include_charts: true
  rate_limit: 30  # messages per second

  notifications:
    signals: true
    errors: true
    daily_summary: true
    performance_metrics: true

monitoring:
  health_check_interval: 60  # seconds
  performance_tracking: true

  alerts:
    system_errors: true
    api_failures: true
    low_confidence_warnings: false

database:
  cache:
    type: "redis"
    ttl: 3600  # seconds

  storage:
    type: "mongodb"
    collections:
      - "market_data"
      - "signals"
      - "performance"
      - "predictions"

logging:
  level: "INFO"
  format: "json"
  rotation: "daily"
  retention_days: 30

  loggers:
    - "market_data"
    - "ai_engine"
    - "signal_generator"
    - "telegram_bot"
    - "performance"
